#pragma once

// check/flag TMC stepper drivers
#if AXIS1_DRIVER_MODEL == TMC2130 || AXIS1_DRIVER_MODEL == TMC5160
  #define AXIS1_DRIVER_TMC_SPI
#endif
#if AXIS2_DRIVER_MODEL == TMC2130 || AXIS2_DRIVER_MODEL == TMC5160
  #define AXIS2_DRIVER_TMC_SPI
#endif
#if AXIS3_DRIVER_MODEL == TMC2130 || AXIS3_DRIVER_MODEL == TMC5160
  #define AXIS3_DRIVER_TMC_SPI
#endif
#if AXIS4_DRIVER_MODEL == TMC2130 || AXIS4_DRIVER_MODEL == TMC5160
  #define AXIS4_DRIVER_TMC_SPI
#endif
#if AXIS5_DRIVER_MODEL == TMC2130 || AXIS5_DRIVER_MODEL == TMC5160
  #define AXIS5_DRIVER_TMC_SPI
#endif
#if AXIS6_DRIVER_MODEL == TMC2130 || AXIS6_DRIVER_MODEL == TMC5160
  #define AXIS6_DRIVER_TMC_SPI
#endif
#if AXIS7_DRIVER_MODEL == TMC2130 || AXIS7_DRIVER_MODEL == TMC5160
  #define AXIS7_DRIVER_TMC_SPI
#endif
#if AXIS8_DRIVER_MODEL == TMC2130 || AXIS8_DRIVER_MODEL == TMC5160
  #define AXIS8_DRIVER_TMC_SPI
#endif
#if AXIS9_DRIVER_MODEL == TMC2130 || AXIS9_DRIVER_MODEL == TMC5160
  #define AXIS9_DRIVER_TMC_SPI
#endif

// common axis driver settings, RA/AZM
#ifndef AXIS1_DRIVER_MICROSTEPS
#define AXIS1_DRIVER_MICROSTEPS       OFF  // normal microstep mode 
#endif
#ifndef AXIS1_DRIVER_MICROSTEPS_GOTO
#define AXIS1_DRIVER_MICROSTEPS_GOTO  OFF  // microstep mode to use during slews
#endif
#ifndef AXIS1_DRIVER_DECAY
#define AXIS1_DRIVER_DECAY            OFF  // OFF for default, TMC STEALTHCHOP
#endif
#ifndef AXIS1_DRIVER_DECAY_GOTO
#define AXIS1_DRIVER_DECAY_GOTO       OFF  // OFF for default, TMC SPREADCYCLE
#endif
#ifndef AXIS1_DRIVER_IHOLD
#define AXIS1_DRIVER_IHOLD            HALF // in mA
#endif
#ifndef AXIS1_DRIVER_IRUN
#define AXIS1_DRIVER_IRUN             OFF  // in mA
#endif
#ifndef AXIS1_DRIVER_IGOTO
#define AXIS1_DRIVER_IGOTO            SAME // in mA
#endif
#ifndef AXIS1_DRIVER_STATUS
#define AXIS1_DRIVER_STATUS           OFF  // driver status reporting (ON for TMC SPI or HIGH/LOW for fault pin)
#endif

// common axis driver settings, DEC/ALT
#ifndef AXIS2_DRIVER_MICROSTEPS
#define AXIS2_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS2_DRIVER_MICROSTEPS_GOTO
#define AXIS2_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS2_DRIVER_DECAY
#define AXIS2_DRIVER_DECAY            OFF
#endif
#ifndef AXIS2_DRIVER_DECAY_GOTO
#define AXIS2_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS2_DRIVER_IHOLD
#define AXIS2_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS2_DRIVER_IRUN
#define AXIS2_DRIVER_IRUN             OFF
#endif
#ifndef AXIS2_DRIVER_IGOTO
#define AXIS2_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS2_DRIVER_STATUS
#define AXIS2_DRIVER_STATUS           OFF
#endif

// common axis driver settings, ROTATOR
#ifndef AXIS3_DRIVER_MICROSTEPS
#define AXIS3_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS3_DRIVER_MICROSTEPS_GOTO
#define AXIS3_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS3_DRIVER_DECAY
#define AXIS3_DRIVER_DECAY            OFF
#endif
#ifndef AXIS3_DRIVER_DECAY_GOTO
#define AXIS3_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS3_DRIVER_IHOLD
#define AXIS3_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS3_DRIVER_IRUN
#define AXIS3_DRIVER_IRUN             OFF
#endif
#ifndef AXIS3_DRIVER_IGOTO
#define AXIS3_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS3_DRIVER_STATUS
#define AXIS3_DRIVER_STATUS           OFF
#endif

// common axis driver settings, FOCUSER1
#ifndef AXIS4_DRIVER_MICROSTEPS
#define AXIS4_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS4_DRIVER_MICROSTEPS_GOTO
#define AXIS4_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS4_DRIVER_DECAY
#define AXIS4_DRIVER_DECAY            OFF
#endif
#ifndef AXIS4_DRIVER_DECAY_GOTO
#define AXIS4_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS4_DRIVER_IHOLD
#define AXIS4_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS4_DRIVER_IRUN
#define AXIS4_DRIVER_IRUN             OFF
#endif
#ifndef AXIS4_DRIVER_IGOTO
#define AXIS4_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS4_DRIVER_STATUS
#define AXIS4_DRIVER_STATUS           OFF
#endif

// common axis driver settings, FOCUSER2
#ifndef AXIS5_DRIVER_MICROSTEPS
#define AXIS5_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS5_DRIVER_MICROSTEPS_GOTO
#define AXIS5_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS5_DRIVER_DECAY
#define AXIS5_DRIVER_DECAY            OFF
#endif
#ifndef AXIS5_DRIVER_DECAY_GOTO
#define AXIS5_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS5_DRIVER_IHOLD
#define AXIS5_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS5_DRIVER_IRUN
#define AXIS5_DRIVER_IRUN             OFF
#endif
#ifndef AXIS5_DRIVER_IGOTO
#define AXIS5_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS5_DRIVER_STATUS
#define AXIS5_DRIVER_STATUS           OFF
#endif

// common axis driver settings, FOCUSER3
#ifndef AXIS6_DRIVER_MICROSTEPS
#define AXIS6_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS6_DRIVER_MICROSTEPS_GOTO
#define AXIS6_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS6_DRIVER_DECAY
#define AXIS6_DRIVER_DECAY            OFF
#endif
#ifndef AXIS6_DRIVER_DECAY_GOTO
#define AXIS6_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS6_DRIVER_IHOLD
#define AXIS6_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS6_DRIVER_IRUN
#define AXIS6_DRIVER_IRUN             OFF
#endif
#ifndef AXIS6_DRIVER_IGOTO
#define AXIS6_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS6_DRIVER_STATUS
#define AXIS6_DRIVER_STATUS           OFF
#endif

// common axis driver settings, FOCUSER4
#ifndef AXIS7_DRIVER_MICROSTEPS
#define AXIS7_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS7_DRIVER_MICROSTEPS_GOTO
#define AXIS7_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS7_DRIVER_DECAY
#define AXIS7_DRIVER_DECAY            OFF
#endif
#ifndef AXIS7_DRIVER_DECAY_GOTO
#define AXIS7_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS7_DRIVER_IHOLD
#define AXIS7_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS7_DRIVER_IRUN
#define AXIS7_DRIVER_IRUN             OFF
#endif
#ifndef AXIS7_DRIVER_IGOTO
#define AXIS7_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS7_DRIVER_STATUS
#define AXIS7_DRIVER_STATUS           OFF
#endif

// common axis driver settings, FOCUSER5
#ifndef AXIS8_DRIVER_MICROSTEPS
#define AXIS8_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS8_DRIVER_MICROSTEPS_GOTO
#define AXIS8_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS8_DRIVER_DECAY
#define AXIS8_DRIVER_DECAY            OFF
#endif
#ifndef AXIS8_DRIVER_DECAY_GOTO
#define AXIS8_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS8_DRIVER_IHOLD
#define AXIS8_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS8_DRIVER_IRUN
#define AXIS8_DRIVER_IRUN             OFF
#endif
#ifndef AXIS8_DRIVER_IGOTO
#define AXIS8_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS8_DRIVER_STATUS
#define AXIS8_DRIVER_STATUS           OFF
#endif

// common axis driver settings, FOCUSER6
#ifndef AXIS9_DRIVER_MICROSTEPS
#define AXIS9_DRIVER_MICROSTEPS       OFF
#endif
#ifndef AXIS9_DRIVER_MICROSTEPS_GOTO
#define AXIS9_DRIVER_MICROSTEPS_GOTO  OFF
#endif
#ifndef AXIS9_DRIVER_DECAY
#define AXIS9_DRIVER_DECAY            OFF
#endif
#ifndef AXIS9_DRIVER_DECAY_GOTO
#define AXIS9_DRIVER_DECAY_GOTO       OFF
#endif
#ifndef AXIS9_DRIVER_IHOLD
#define AXIS9_DRIVER_IHOLD            HALF
#endif
#ifndef AXIS9_DRIVER_IRUN
#define AXIS9_DRIVER_IRUN             OFF
#endif
#ifndef AXIS9_DRIVER_IGOTO
#define AXIS9_DRIVER_IGOTO            SAME
#endif
#ifndef AXIS9_DRIVER_STATUS
#define AXIS9_DRIVER_STATUS           OFF
#endif

#if AXIS1_DRIVER_MODEL != OFF
  #define AXIS1_SUBDIVISIONS  AXIS1_DRIVER_MICROSTEPS
  #define AXIS1_CURRENT       AXIS1_DRIVER_IRUN
#endif
#if AXIS2_DRIVER_MODEL != OFF
  #define AXIS2_SUBDIVISIONS  AXIS2_DRIVER_MICROSTEPS
  #define AXIS2_CURRENT       AXIS2_DRIVER_IRUN
#endif
#if AXIS3_DRIVER_MODEL != OFF
  #define AXIS3_SUBDIVISIONS  AXIS3_DRIVER_MICROSTEPS
  #define AXIS3_CURRENT       AXIS3_DRIVER_IRUN
#endif
#if AXIS4_DRIVER_MODEL != OFF
  #define AXIS4_SUBDIVISIONS  AXIS4_DRIVER_MICROSTEPS
  #define AXIS4_CURRENT       AXIS4_DRIVER_IRUN
#endif
#if AXIS5_DRIVER_MODEL != OFF
  #define AXIS5_SUBDIVISIONS  AXIS5_DRIVER_MICROSTEPS
  #define AXIS5_CURRENT       AXIS5_DRIVER_IRUN
#endif
#if AXIS6_DRIVER_MODEL != OFF
  #define AXIS6_SUBDIVISIONS  AXIS6_DRIVER_MICROSTEPS
  #define AXIS6_CURRENT       AXIS6_DRIVER_IRUN
#endif
#if AXIS7_DRIVER_MODEL != OFF
  #define AXIS7_SUBDIVISIONS  AXIS7_DRIVER_MICROSTEPS
  #define AXIS7_CURRENT       AXIS7_DRIVER_IRUN
#endif
#if AXIS8_DRIVER_MODEL != OFF
  #define AXIS8_SUBDIVISIONS  AXIS8_DRIVER_MICROSTEPS
  #define AXIS8_CURRENT       AXIS8_DRIVER_IRUN
#endif
#if AXIS9_DRIVER_MODEL != OFF
  #define AXIS9_SUBDIVISIONS  AXIS9_DRIVER_MICROSTEPS
  #define AXIS9_CURRENT       AXIS9_DRIVER_IRUN
#endif
