#pragma once
#include "Axis.h"
#include "Transform.h"
#include "StepDriver.h"

// 
double axis1_steps_per_radian = radToDeg(AXIS1_STEPS_PER_DEGREE);
double axis2_steps_per_radian = radToDeg(AXIS2_STEPS_PER_DEGREE);

// stepper drivers
#if AXIS1_DRIVER != OFF
  Axis axis1{AXIS1_STEP_PIN, AXIS1_DIR_PIN, AXIS1_ENABLE_PIN};
  StepDriver axis1Driver{AXIS1_M0_PIN, AXIS1_M1_PIN, AXIS1_M2_PIN, AXIS1_M3_PIN, AXIS1_DECAY_PIN};
  DriverSettings axis1DriverSettings = {AXIS1_DRIVER,AXIS1_DRIVER_MICROSTEPS,AXIS1_DRIVER_MICROSTEPS_GOTO,AXIS1_DRIVER_IHOLD,AXIS1_DRIVER_IRUN,AXIS1_DRIVER_IGOTO,AXIS1_DRIVER_DECAY,AXIS1_DRIVER_DECAY_GOTO};
#endif
#if AXIS2_DRIVER != OFF
  Axis axis2{AXIS2_STEP_PIN, AXIS2_DIR_PIN, AXIS2_ENABLE_PIN};
  StepDriver axis2Driver{AXIS1_M0_PIN, AXIS1_M1_PIN, AXIS1_M2_PIN, AXIS1_M3_PIN, AXIS1_DECAY_PIN};
  DriverSettings axis2DriverSettings = {AXIS2_DRIVER,AXIS2_DRIVER_MICROSTEPS,AXIS2_DRIVER_MICROSTEPS_GOTO,AXIS2_DRIVER_IHOLD,AXIS2_DRIVER_IRUN,AXIS2_DRIVER_IGOTO,AXIS2_DRIVER_DECAY,AXIS2_DRIVER_DECAY_GOTO};
#endif
#if AXIS3_DRIVER != OFF
  Axis axis1{AXIS3_STEP_PIN, AXIS3_DIR_PIN, AXIS3_ENABLE_PIN};
  StepDriver axis3Driver{AXIS1_M3_PIN, AXIS1_M3_PIN, AXIS3_M2_PIN, AXIS3_M3_PIN, AXIS3_DECAY_PIN};
  DriverSettings axis3DriverSettings = {AXIS3_DRIVER,AXIS3_DRIVER_MICROSTEPS,AXIS3_DRIVER_MICROSTEPS_GOTO,AXIS3_DRIVER_IHOLD,AXIS3_DRIVER_IRUN,AXIS3_DRIVER_IGOTO,AXIS3_DRIVER_DECAY,AXIS3_DRIVER_DECAY_GOTO};
#endif
#if AXIS4_DRIVER != OFF
  Axis axis4{AXIS4_STEP_PIN, AXIS4_DIR_PIN, AXIS4_ENABLE_PIN};
  StepDriver axis4Driver{AXIS4_M0_PIN, AXIS4_M1_PIN, AXIS4_M2_PIN, AXIS4_M3_PIN, AXIS4_DECAY_PIN};
  DriverSettings axis4DriverSettings = {AXIS4_DRIVER,AXIS4_DRIVER_MICROSTEPS,AXIS4_DRIVER_MICROSTEPS_GOTO,AXIS4_DRIVER_IHOLD,AXIS4_DRIVER_IRUN,AXIS4_DRIVER_IGOTO,AXIS4_DRIVER_DECAY,AXIS4_DRIVER_DECAY_GOTO};
#endif
#if AXIS5_DRIVER != OFF
  Axis axis5{AXIS5_STEP_PIN, AXIS5_DIR_PIN, AXIS5_ENABLE_PIN};
  StepDriver axis5Driver{AXIS1_M5_PIN, AXIS1_M5_PIN, AXIS5_M2_PIN, AXIS5_M3_PIN, AXIS5_DECAY_PIN};
  DriverSettings axis5DriverSettings = {AXIS5_DRIVER,AXIS5_DRIVER_MICROSTEPS,AXIS5_DRIVER_MICROSTEPS_GOTO,AXIS5_DRIVER_IHOLD,AXIS5_DRIVER_IRUN,AXIS5_DRIVER_IGOTO,AXIS5_DRIVER_DECAY,AXIS5_DRIVER_DECAY_GOTO};
#endif
#if AXIS6_DRIVER != OFF
  Axis axis6{AXIS6_STEP_PIN, AXIS6_DIR_PIN, AXIS6_ENABLE_PIN};
  StepDriver axis6Driver{AXIS6_M0_PIN, AXIS6_M1_PIN, AXIS6_M2_PIN, AXIS6_M3_PIN, AXIS6_DECAY_PIN};
  DriverSettings axis6DriverSettings = {AXIS6_DRIVER,AXIS6_DRIVER_MICROSTEPS,AXIS6_DRIVER_MICROSTEPS_GOTO,AXIS6_DRIVER_IHOLD,AXIS6_DRIVER_IRUN,AXIS6_DRIVER_IGOTO,AXIS6_DRIVER_DECAY,AXIS6_DRIVER_DECAY_GOTO};
#endif

// Error codes
GeneralErrors generalError = ERR_NONE;
