// -----------------------------------------------------------------------------------
// Common includes
#pragma once

#include <Arduino.h>
#include "Constants.h"
#include "lib/Constants.h"
#include "lib/Macros.h"
#include "Config.common.h"
#include "HAL/HAL.h"
#include "pinmaps/Models.h"
#include "lib/debug/Debug.h"
#include "lib/nv/NV.h"
extern NVS nv;

#define SERIAL_LOCAL_MODE ON
#define SERIAL_ST4_MASTER ON

#if (AXIS1_DRIVER_MODEL != OFF && AXIS2_DRIVER_MODEL != OFF) || AXIS3_DRIVER_MODEL != OFF || AXIS4_DRIVER_MODEL != OFF || AXIS5_DRIVER_MODEL != OFF || AXIS6_DRIVER_MODEL != OFF || AXIS7_DRIVER_MODEL != OFF || AXIS8_DRIVER_MODEL != OFF || AXIS9_DRIVER_MODEL != OFF
  #define AXIS_PRESENT
#endif

#if AXIS1_DRIVER_MODEL != OFF && AXIS2_DRIVER_MODEL != OFF
  #define MOUNT_PRESENT
#endif

#if AXIS3_DRIVER_MODEL != OFF
  #define ROTATOR_PRESENT
#endif

#if AXIS4_DRIVER_MODEL != OFF || AXIS5_DRIVER_MODEL != OFF || AXIS6_DRIVER_MODEL != OFF || AXIS7_DRIVER_MODEL != OFF || AXIS8_DRIVER_MODEL != OFF || AXIS9_DRIVER_MODEL != OFF
  #define FOCUSER_PRESENT
#endif

#if FEATURE1_PURPOSE != OFF || FEATURE2_PURPOSE != OFF || FEATURE3_PURPOSE != OFF || FEATURE4_PURPOSE != OFF || FEATURE5_PURPOSE != OFF || FEATURE6_PURPOSE != OFF || FEATURE7_PURPOSE != OFF || FEATURE8_PURPOSE != OFF
  #define FEATURES_PRESENT
#endif

#if FEATURE1_PURPOSE == DEW_HEATER || FEATURE2_PURPOSE == DEW_HEATER || FEATURE3_PURPOSE == DEW_HEATER || FEATURE4_PURPOSE == DEW_HEATER || FEATURE5_PURPOSE == DEW_HEATER || FEATURE6_PURPOSE == DEW_HEATER || FEATURE7_PURPOSE == DEW_HEATER || FEATURE8_PURPOSE == DEW_HEATER
  #define DEW_HEATER_PRESENT

  #if (FEATURE1_TEMP & DS_MASK) == DS1820  || (FEATURE2_TEMP & DS_MASK) == DS1820  || (FEATURE3_TEMP & DS_MASK) == DS1820  || (FEATURE4_TEMP & DS_MASK) == DS1820  || \
      (FEATURE5_TEMP & DS_MASK) == DS1820  || (FEATURE6_TEMP & DS_MASK) == DS1820  || (FEATURE7_TEMP & DS_MASK) == DS1820  || (FEATURE8_TEMP & DS_MASK) == DS1820  || \
      (FEATURE1_TEMP & DS_MASK) == DS18S20 || (FEATURE2_TEMP & DS_MASK) == DS18S20 || (FEATURE3_TEMP & DS_MASK) == DS18S20 || (FEATURE4_TEMP & DS_MASK) == DS18S20 || \
      (FEATURE5_TEMP & DS_MASK) == DS18S20 || (FEATURE6_TEMP & DS_MASK) == DS18S20 || (FEATURE7_TEMP & DS_MASK) == DS18S20 || (FEATURE8_TEMP & DS_MASK) == DS18S20
    #define DS1820_DEVICES_PRESENT
  #endif

  #if FEATURE1_TEMP == THERMISTOR1 || FEATURE2_TEMP == THERMISTOR1 || FEATURE3_TEMP == THERMISTOR1 || FEATURE4_TEMP == THERMISTOR1 || \
      FEATURE5_TEMP == THERMISTOR1 || FEATURE6_TEMP == THERMISTOR1 || FEATURE7_TEMP == THERMISTOR1 || FEATURE8_TEMP == THERMISTOR1 || \
      FEATURE1_TEMP == THERMISTOR2 || FEATURE2_TEMP == THERMISTOR2 || FEATURE3_TEMP == THERMISTOR2 || FEATURE4_TEMP == THERMISTOR2 || \
      FEATURE5_TEMP == THERMISTOR2 || FEATURE6_TEMP == THERMISTOR2 || FEATURE7_TEMP == THERMISTOR2 || FEATURE8_TEMP == THERMISTOR2
    #define THERMISTOR_DEVICES_PRESENT
  #endif
#endif

#if (FOCUSER_TEMPERATURE & DS_MASK) == DS1820 || (FOCUSER_TEMPERATURE & DS_MASK) == DS18S20
  #ifndef DS1820_DEVICES_PRESENT
    #define DS1820_DEVICES_PRESENT
  #endif
#endif

#if FOCUSER_TEMPERATURE == THERMISTOR1 || FOCUSER_TEMPERATURE == THERMISTOR2
  #ifndef THERMISTOR_DEVICES_PRESENT
    #define THERMISTOR_DEVICES_PRESENT
  #endif
#endif

#include "lib/gpio/Gpio.h"
